import os

SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
WORLD_HEIGHT = 2000
VIEWPORT_HEIGHT = 600
VIEWPORT_WIDTH = 800
FPS = 60
HORIZON_Y = WORLD_HEIGHT * 0.8

ASSETS_DIR = 'assets'
SOUNDS_DIR = os.path.join(ASSETS_DIR, 'sounds')